apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-summaraidGPT-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: select
          name: modelType
          key: modelType
          id: modelType
          label: 大模型类型
          searchable: true
          placeholder: 请选择你的大模型类型
          options:
            - label: OpenAi
              value: openAi
            - label: 千帆
              value: qianfan
            - label: 智谱
              value: zhipuAi
            - label: 通义千问
              value: dashScope
            - label: Ollama
              value: ollama
        - $formkit: text
          if: $get(modelType).value == "qianfan"
          name: clientId
          label: ApiKey
          placeholder: 请输入千帆ModelBuilder的应用介入的ApiKey
          validation: required
          help: 必填,请前往https://console.bce.baidu.com/qianfan/overview 应用介入获取ApiKey
        - $formkit: text
          if: $get(modelType).value == "qianfan"
          name: clientSecret
          label: SecretKey
          placeholder: 请输入千帆ModelBuilder的应用介入的SecretKey
          validation: required
          help: 必填,请前往https://console.bce.baidu.com/qianfan/overview SecretKey
        - $formkit: text
          name: aiSystem
          label: 模型人设
          placeholder: 请输入模型人设
          help: 模型人设，主要用于人设设定，例如：你好,你是一个专业写200字左右文章摘要总结写手,不写为默认值
    - group: summary
      label: 摘要设置
      formSchema:
        - $el: a
          attrs:
            href: "https://www.halo.run/store/apps/app-riNgb"
            class: "py-4 block"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
              target: "_blank"
          children:
            - $el: span
              children: "查看 Ink AI 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/ai-assistant/assets/static/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $formkit: checkbox
          label: 开启文章摘要
          name: enableSummary
          id: enableSummary
          key: enableSummary
          value: true
          help: "开启文章摘要需要在基础设置中完成ApiKey和SecretKey"
        - $formkit: checkbox
          label: 开启主题适配
          name: enableTemplate
          id: enableTemplate
          key: enableTemplate
          value: false
          help: "开启此项后,插件只请求AI摘要,不会植入JS和CSS相关资源"
        - $formkit: text
          label: 文章选择器
          if: $get(enableTemplate).value == false
          name: postSelector
          id: postSelector
          key: postSelector
          value: "article"
          help: "文章选择器，用于选择文章内容。可以填写标签也可以填写标签ID 注意ID需要通过#开头"
        - $formkit: text
          label: 摘要标题
          if: $get(enableTemplate).value == false
          name: title
          id: title
          key: title
          value: "文章摘要"
          help: "摘要标题，用于显示在摘要顶部的自定义内容"
        - $formkit: attachment
          if: $get(enableTemplate).value == false
          label: 摘要样式css
          name: summaryStyle
          id: summaryStyle
          key: summaryStyle
          value: "https://www.lik.cc/upload/ArticleSummary.css"
          help: "摘要样式css地址，可以通过https://github.com/acanyo/halo-aipost-summaraidGPT 给我提交PR，欢迎你的共建"
        - $formkit: textarea
          label: 文章路由
          name: postURL
          id: postURL
          key: postURL
          value: "*/archives/*"
          help: "在符合url条件的网页执行文章摘要功能，通常清况下，绝大多数Halo网站使用默认配置即可，无需调整"
        - $formkit: textarea
          label: 黑名单
          name: blacklist
          id: blacklist
          key: blacklist
          help: "黑名单URL,多个用,隔开注意是英文逗号，如 填写相关的网址地址多个回车"
        - $formkit: attachment
          label: 自定义图标
          if: $get(enableTemplate).value == false
          name: customizeIco
          id: customizeIco
          key: customizeIco
          value: "https://www.lik.cc/upload/icon.svg"
          help: 用于显示在摘要顶部的图标,目前支持png,jpg,webp,svg,其他图片格式未测试
        - $formkit: text
          if: $get(enableTemplate).value == false
          label: 自定义开头语
          name: source
          id: source
          key: source
          value: "LIK.CC-GPT"
          help: "用于显示在摘要顶部的描述"
        - $formkit: text
          if: $get(enableTemplate).value == false
          label: 样式选择器
          name: darkModeSelector
          id: darkModeSelector
          key: darkModeSelector
          value: ""
          help: "用于自动判断主题是否暗色模式自动切换,为空默认不切换"
        #        - $formkit: text
        #          label: 自定义描述宽度
        #          name: summaryWidth
        #          id: summaryWidth
        #          key: summaryWidth
        #          value: ""
        #          help: "用户文章内宽>内容造成插件溢出问题,建议不修改,为空默认不修改"
        - $formkit: select
          name: summaryTheme
          key: summaryTheme
          id: summaryTheme
          if: $get(enableTemplate).value == false
          label: 摘要样式
          sortable: true
          clearable: true
          searchable: true
          placeholder: 请选择你的主题
          options:
            - label: 默认主题
              value: default
            - label: 精简主题
              value: simple
            - label: 七彩主题
              value: yanzhi
            - label: 模糊主题
              value: menghuan
            - label: 暗色主题
              value: dark
