apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-summaraidGPT-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $el: a
          attrs:
            href: "https://docs.lik.cc"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "查看 Ink 智阅GPT 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/summaraidGPT/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "Halo交流群"
        - $el: img
          attrs:
            src: "https://www.lik.cc/upload/iShot_2025-03-03_16.03.00.png"
            width: "100px"
            height: "120px"
            style:
              margin-left: "80px"
#        - $formkit: checkbox
#          label: 关闭全局摘要
#          name: enableAi
#          id: enableAi
#          key: enableAi
#          value: false
#          help: "关闭后不再产生AI摘要"
        - $formkit: select
          name: modelType
          key: modelType
          id: modelType
          label: 大模型类型
          searchable: true
          placeholder: 请选择你的大模型类型
          options:
            - label: OpenAi
              value: openAi
            - label: 智谱
              value: zhipuAi
            - label: 通义千问
              value: dashScope
            - label: API加速站
              value: codesphere
#          OpenAi
        - $formkit: password
          if: $get(modelType).value === "codesphere"
          name: codesphereKey
          id: codesphereKey
          key: codesphereKey
          label: Codesphere密钥
        - $el: div
          if: $get(modelType).value === "codesphere"
          attrs:
            class: "formkit-help text-xs text-gray-500"
            innerHTML: "国内加速站 <a href='https://api.codesphere.chat/register?aff=76JI' title='前往 Codesphere 免费获取 Key' target='_blank' class='text-blue-500 hover:text-blue-700'>Codesphere 注册并获取专属免费 Key</a>，解锁更快的响应速度。"
        - $formkit: text
          if: $get(modelType).value === "codesphere"
          name: codesphereType
          id: codesphereType
          key: codesphereType
          label: Codesphere模型类型
        - $el: div
          if: $get(modelType).value === "codesphere"
          attrs:
            class: "formkit-help text-xs text-gray-500"
            innerHTML: "国内加速站 <a href='https://api.codesphere.chat/pricing' title='前往 Codesphere 模型' target='_blank' class='text-blue-500 hover:text-blue-700'>Codesphere 模型类型</a>，推荐免费的智普推理模型。"

        - $formkit: password
          if: $get(modelType).value == "openAi"
          name: openAiApiKey
          key: openAiApiKey
          label: API密钥
          placeholder: 请输入openAi的应用介入的ApiKey
          validation: required
          help: 必填,请前往 OpenAi 应用介入获取ApiKey
        - $formkit: text
          if: $get(modelType).value == "openAi"
          name: openAiModelName
          key: openAiModelName
          label: 模型名称
          placeholder: 请输入Openai的模型名称
          validation: required
          help: 必填,请前往 OpenAi 应用介入获取模型名称
        - $formkit: text
          if: $get(modelType).value == "openAi"
          name: baseUrl
          key: baseUrl
          label: API地址
          placeholder: https://api.openai.com/
          help: 只需填写基础API地址，系统会自动拼接端点路径
#          智谱大模型
        - $formkit: password
          if: $get(modelType).value == "zhipuAi"
          name: zhipuAiApiKey
          key: zhipuAiApiKey
          label: 智谱API密钥
          placeholder: 请输入 智谱 的应用介入的ApiKey
          validation: required
          help: 必填,请前往 智谱 应用介入获取ApiKey
        - $formkit: text
          if: $get(modelType).value == "zhipuAi"
          name: zhipuAiModelName
          key: zhipuAiModelName
          label: 智谱模型名称
          placeholder: 请输入智谱的模型名称
          validation: required
          help: 必填,请前往 智谱 应用介入获取模型名称
        #          通义千问
        - $formkit: password
          if: $get(modelType).value == "dashScope"
          name: dashScopeApiKey
          key: dashScopeApiKey
          label: 通义千问API密钥
          placeholder: 请输入 通义千问 的应用介入的ApiKey
          validation: required
          help: 必填,请前往 通义千问 应用介入获取ApiKey
        - $formkit: text
          if: $get(modelType).value == "dashScope"
          name: dashScopeModelName
          key: dashScopeModelName
          label: 通义千问模型名称
          placeholder: 请输入 通义千问 的模型名称
          validation: required
          help: 必填,请前往 通义千问 应用介入获取模型名称
        - $formkit: text
          name: aiSystem
          key: aiSystem
          label: 模型人设
          placeholder: 请输入模型人设
          help: 模型人设，主要用于人设设定，例如：你好,你是一个专业写200字左右文章摘要总结写手,不写为默认值
    - group: summary
      label: 摘要设置
      formSchema:
        - $formkit: text
          label: 摘要框标题
          name: summaryTitle
          id: summaryTitle
          key: summaryTitle
          value: "文章摘要"
          help: "摘要框显示的标题"
        - $formkit: text
          label: AI模型名称
          name: gptName
          id: gptName
          key: gptName
          value: "智阅GPT"
          help: "AI模型名称，显示在摘要框中"
        - $formkit: text
          label: 目标元素选择器
          name: target
          id: target
          key: target
          value: ".article-content"
          help: "摘要框插入的目标元素选择器"
        - $formkit: text
          label: 文章路由
          name: whitelist
          id: whitelist
          key: whitelist
          value: "/archives/*"
          help: "只在指定路径下显示摘要框，多个路径用逗号分隔"
        - $formkit: text
          label: 深色模式选择器
          name: darkSelector
          id: darkSelector
          key: darkSelector
          value: "data-theme=dark"
          help: "用于自动判断深色模式的选择器"
        - $formkit: number
          label: 打字机速度
          name: typeSpeed
          id: typeSpeed
          key: typeSpeed
          value: 20
          help: "打字机动画速度（毫秒/字符）"
        - $formkit: checkbox
          label: 启用打字机效果
          name: typewriter
          id: typewriter
          key: typewriter
          value: true
          help: "是否启用打字机效果"
    - group: style
      label: 样式设置
      formSchema:
        - $formkit: select
          name: themeName
          key: themeName
          id: themeName
          label: 主题选择
          value: "custom"
          placeholder: "请选择主题"
          options:
            - label: 自定义主题
              value: custom
            - label: 蓝色主题
              value: blue
            - label: 默认主题
              value: default
            - label: 暗色主题
              value: dark
            - label: 绿色主题
              value: green
          help: "选择主题类型，自定义主题使用下方配色设置"
        - $formkit: attachment
          label: Logo图片
          name: logo
          id: logo
          key: logo
          value: "/plugins/summaraidGPT/assets/static/icon.svg"
          help: "摘要框Logo图片路径"
        - $formkit: text
          label: 背景色
          if: $get(themeName).value == "custom"
          name: themeBg
          id: themeBg
          key: themeBg
          value: "#f7f9fe"
        - $el: div
          if: $get(themeName).value == "custom"
          attrs:
            class: "formkit-help text-xs text-gray-500"
            innerHTML: "摘要框背景色，支持纯色和渐变色，如：linear-gradient(45deg, #f7f9fe, #e3e8f7)<a href='https://pxlab.cn/color/index.html' title='前往获取渐变色' target='_blank' class='text-blue-500 hover:text-blue-700'>获取渐变色</a>"
        - $formkit: color
          label: 主色调
          if: $get(themeName).value == "custom"
          name: themeMain
          id: themeMain
          key: themeMain
          value: "#4F8DFD"
          help: "主色调，用于边框和强调"
        - $formkit: color
          label: 标题颜色
          if: $get(themeName).value == "custom"
          name: themeTitle
          id: themeTitle
          key: themeTitle
          value: "#3A5A8C"
          help: "标题文字颜色"
        - $formkit: color
          label: 内容颜色
          if: $get(themeName).value == "custom"
          name: themeContent
          id: themeContent
          key: themeContent
          value: "#222"
          help: "内容文字颜色"
        - $formkit: color
          label: AI名称颜色
          if: $get(themeName).value == "custom"
          name: themeGptName
          id: themeGptName
          key: themeGptName
          value: "#7B88A8"
          help: "AI模型名称颜色"
        - $formkit: color
          label: 内容背景色
          if: $get(themeName).value == "custom"
          name: themeContentBg
          id: themeContentBg
          key: themeContentBg
          value: "#fff"
          help: "内容区域背景色"
        - $formkit: color
          label: 边框颜色
          if: $get(themeName).value == "custom"
          name: themeBorder
          id: themeBorder
          key: themeBorder
          value: "#e3e8f7"
          help: "边框颜色"
        - $formkit: text
          label: 阴影效果
          if: $get(themeName).value == "custom"
          name: themeShadow
          id: themeShadow
          key: themeShadow
          value: "0 2px 12px 0 rgba(60,80,180,0.08)"
          help: "阴影效果CSS值"
        - $formkit: color
          label: 标签背景色
          if: $get(themeName).value == "custom"
          name: themeTagBg
          id: themeTagBg
          key: themeTagBg
          value: "#f0f4ff"
          help: "标签背景色"
        - $formkit: color
          label: 光标颜色
          if: $get(themeName).value == "custom"
          name: themeCursor
          id: themeCursor
          key: themeCursor
          value: "#4F8DFD"
          help: "打字机光标颜色"
        - $formkit: text
          label: 内容字体大小
          if: $get(themeName).value == "custom"
          name: themeContentFontSize
          id: themeContentFontSize
          key: themeContentFontSize
          value: "16px"
          help: "内容文字字体大小"
